# -*- coding: utf-8 -*-
"""Combined_text-emotion-color_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9-Qc21wsp3yk6rxXEm3vT9Yh6c7CkCQ
"""

# -*- coding: utf-8 -*-
"""
Combined Script for Emotion-Based Diary Background Color Recommendation
"""

import pandas as pd
import re
import numpy as np
import colorsys
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ==============================================================================
# PART 1: TEXT-TO-EMOTION MODEL (from acdt_model_v1_text_to_emotion.py)
# ==============================================================================

print("--- Initializing Text-to-Emotion Model ---")

# --- 1.1. Data Loading ---
# Note: Please ensure 'emotion_sentimen_dataset.csv' is in the same directory
# or provide the full path to the file.
try:
    text_emotion_df = pd.read_csv('emotion_sentimen_dataset.csv', encoding='latin1', on_bad_lines='skip')
except FileNotFoundError:
    print("Error: 'emotion_sentimen_dataset.csv' not found.")
    print("Please make sure the dataset for the text-to-emotion model is available.")
    raise

# --- 1.2. Data Cleaning (English text only) ---
try:
    df_renamed = text_emotion_df.rename(columns={'Emotion': 'label', 'text': 'text'})
    df_clean = df_renamed[['text', 'label']]
except KeyError:
    print("Error: 'text' or 'Emotion' column not found in the text emotion dataset.")
    raise

def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df_clean['text'] = df_clean['text'].apply(clean_text)
df_clean.dropna(subset=['text', 'label'], inplace=True)
df_final = df_clean[df_clean['text'] != ""]

# --- 1.3. Label Mapping (excluding 'neutral') ---
label_map = {
    'happiness': 'Happiness', 'fun': 'Happiness', 'enthusiasm': 'Happiness',
    'relief': 'Happiness', 'love': 'Happiness', 'sadness': 'Sadness',
    'empty': 'Sadness', 'boredom': 'Sadness', 'anger': 'Anger',
    'worry': 'Fear', 'hate': 'Disgust', 'surprise': 'Surprise'
}
df_final['label'] = df_final['label'].map(label_map)
df_final = df_final.dropna(subset=['label'])

# --- 1.4. Training/Test Data Split ---
X_text = df_final['text']
y_text = df_final['label']
X_train_text, X_test_text, y_train_text, y_test_text = train_test_split(
    X_text, y_text, test_size=0.2, random_state=42, stratify=y_text
)

# --- 1.5. TF-IDF Vectorization ---
tfidf_vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_text)
X_test_tfidf = tfidf_vectorizer.transform(X_test_text)

# --- 1.6. Model Training ---
text_emotion_model = LogisticRegression(
    max_iter=1000, random_state=42, class_weight='balanced'
)
print("Training the text-to-emotion model...")
text_emotion_model.fit(X_train_tfidf, y_train_text)
print("Text-to-emotion model training complete.")

# --- 1.7. Prediction Function for Text ---
def predict_emotion_from_text(diary_entry):
    cleaned_text = clean_text(diary_entry)
    text_vector = tfidf_vectorizer.transform([cleaned_text])
    prediction = text_emotion_model.predict(text_vector)
    return prediction[0]

# ==============================================================================
# PART 2: EMOTION-TO-COLOR RECOMMENDATION MODEL (from colorchoosing.py)
# ==============================================================================

print("\n--- Initializing Emotion-to-Color Recommendation Model ---")

# --- 2.1. Data Loading ---
# IMPORTANT: Replace 'your_file_name.csv' with the actual name of your color-emotion CSV file.
try:
    color_emotion_file_path = 'your_file_name.csv'
    color_data = pd.read_csv(color_emotion_file_path)
except FileNotFoundError:
    print(f"Error: '{color_emotion_file_path}' not found.")
    print("Please replace 'your_file_name.csv' with the correct file path for the color-emotion data.")
    raise

# --- 2.2. Feature and Label Separation ---
X_color = color_data[['h', 's', 'v']]
y_color = color_data['emotion']

# --- 2.3. Label Encoding ---
color_label_encoder = LabelEncoder()
y_encoded_color = color_label_encoder.fit_transform(y_color)

# --- 2.4. Training/Test Data Split ---
X_train_color, X_test_color, y_train_color, y_test_color = train_test_split(
    X_color, y_encoded_color, test_size=0.2, random_state=42
)

# --- 2.5. Model Training ---
color_recommendation_model = RandomForestClassifier(n_estimators=100, random_state=42)
print("Training the emotion-to-color recommendation model...")
color_recommendation_model.fit(X_train_color, y_train_color)
print("Emotion-to-color model training complete.")

# --- 2.6. Color Tone Adjustment Functions ---
def to_bright_pastel_hsv(hsv_color):
    h, s, v = hsv_color
    pastel_s = max(0.1, min(0.4, s * 0.5))
    pastel_v = max(0.8, min(1.0, v * 0.2 + 0.8))
    return (h, pastel_s, pastel_v)

def to_dark_calm_hsv(hsv_color):
    h, s, v = hsv_color
    dark_s = max(0.2, min(0.7, s * 0.7))
    dark_v = max(0.2, min(0.6, v * 0.6))
    return (h, dark_s, dark_v)

# ==============================================================================
# PART 3: COMBINED WORKFLOW
# ==============================================================================

# --- 3.1. User Input for Diary Entry ---
diary_entry = input("\nPlease enter your diary entry: ")

# --- 3.2. Predict Emotion from Text ---
predicted_emotion = predict_emotion_from_text(diary_entry)
print(f"\nPredicted Emotion: {predicted_emotion}")

# --- 3.3. Recommend Color Based on Emotion ---
try:
    selected_encoded_label = color_label_encoder.transform([predicted_emotion])[0]

    # Filter training data for samples the model predicts as the selected emotion
    y_train_pred_color = color_recommendation_model.predict(X_train_color)
    filtered_indices = np.where(y_train_pred_color == selected_encoded_label)[0]

    if len(filtered_indices) > 0:
        # Randomly select one of the filtered samples
        random_index = np.random.choice(filtered_indices)
        selected_hsv_color = tuple(X_train_color.iloc[random_index].values)
    else:
        # Fallback to predefined colors if no samples are found
        print(f"Warning: No training samples were predicted as '{predicted_emotion}'. Using a predefined color.")
        emotion_colors_hsv = {
            'Anger': (0.0, 0.8, 0.7), 'Disgust': (0.33, 0.7, 0.6),
            'Fear': (0.67, 0.8, 0.5), 'Happiness': (0.17, 0.7, 0.8),
            'Sadness': (0.6, 0.5, 0.4), 'Surprise': (0.5, 0.6, 0.9)
        }
        selected_hsv_color = emotion_colors_hsv.get(predicted_emotion, (0.5, 0.5, 0.8)) # Default color if emotion is not in the map

except ValueError:
    print(f"Warning: The emotion '{predicted_emotion}' was not found in the color model's training data. Using a predefined color.")
    emotion_colors_hsv = {
        'Anger': (0.0, 0.8, 0.7), 'Disgust': (0.33, 0.7, 0.6),
        'Fear': (0.67, 0.8, 0.5), 'Happiness': (0.17, 0.7, 0.8),
        'Sadness': (0.6, 0.5, 0.4), 'Surprise': (0.5, 0.6, 0.9)
    }
    selected_hsv_color = emotion_colors_hsv.get(predicted_emotion, (0.5, 0.5, 0.8))


# --- 3.4. Adjust Color Tone Based on Emotion ---
negative_emotions = ['Anger', 'Disgust', 'Fear', 'Sadness']
if predicted_emotion in negative_emotions:
    corrected_hsv_color = to_dark_calm_hsv(selected_hsv_color)
    tone_label = 'Dark & Calm Tone'
else:
    corrected_hsv_color = to_bright_pastel_hsv(selected_hsv_color)
    tone_label = 'Bright Pastel Tone'

# --- 3.5. Convert Colors to RGB and Visualize ---
original_rgb = colorsys.hsv_to_rgb(*selected_hsv_color)
corrected_rgb = colorsys.hsv_to_rgb(*corrected_hsv_color)

print(f"Original Recommended HSV Color: {selected_hsv_color}")
print(f"Adjusted HSV Color for {tone_label}: {corrected_hsv_color}")

# Visualization
fig, ax = plt.subplots(1, 2, figsize=(10, 5))

# Original Color
ax[0].add_patch(patches.Rectangle((0, 0), 1, 1, facecolor=original_rgb))
ax[0].set_title('Original Recommended Color')
ax[0].axis('off')
ax[0].text(0.5, 0.5, f'RGB: ({original_rgb[0]:.2f}, {original_rgb[1]:.2f}, {original_rgb[2]:.2f})',
           color='white' if sum(original_rgb)/3 < 0.5 else 'black', ha='center', va='center')

# Corrected Color
ax[1].add_patch(patches.Rectangle((0, 0), 1, 1, facecolor=corrected_rgb))
ax[1].set_title(f'Adjusted Color: {tone_label}')
ax[1].axis('off')
ax[1].text(0.5, 0.5, f'RGB: ({corrected_rgb[0]:.2f}, {corrected_rgb[1]:.2f}, {corrected_rgb[2]:.2f})',
           color='white' if sum(corrected_rgb)/3 < 0.5 else 'black', ha='center', va='center')

plt.suptitle(f'Color Recommendation for Emotion: {predicted_emotion}', fontsize=16)
plt.show()